version: '3.8'

networks:
  database:
  app-network:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - database

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    networks:
      - database

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - database

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - database
  webapp_react:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    networks:
      - app-network

  webapp_nest:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - postgres
      - mysql
      - mongodb
      - redis
      - api_golang
      - api_nodejs
      - api_nest
      - webapp_react
      - webapp_nest

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  redis_data:

